LLVM: Switch native flag from -march=native to -mtune=native -mcpu=native for aarch64
It was observed that `-march=native` does not actually provide all the CPU
features on e.g. GH200, missing bf16 when building OpenBLAS 0.3.31 with
LLVM 21.1.8. This causes build failures like:

../kernel/arm64/sbgemv_n_neon.c:146:14: error: '__builtin_neon_vld1q_bf16' needs target feature bf16,neon
  146 |         a3 = vld1q_bf16(a_ptr3);
      |              ^

Switching to -mtune=native -mcpu=native solves this issue. Therefore, apply
this option generally.

Signed-off-by: Jan André Reuter <j.reuter@fz-juelich.de>