Don't print location of LoggedException constructor as source of error.
`caller_info` will return the direct caller which is not useful in this case
as every log will look like:

>  build_log.py:226 ERROR EasyBuild encountered an error (at easybuild/base/exceptions.py:126 in __init__): [...]