Fix "AttributeError: 'bool' object has no attribute 'info'" in calls to `print_msg()` and `print_error()`
Functions `print_msg` and `print_error` have an argument called `log`, which should apparently cause both functions to echo the message to the EB log file and not just to the screen.  However, the logger object is also called `log` (module-level global), and the local parameter binding shadows the module-level one.

As a result, `print_msg("foo", log=True)` errors out with `AttributeError: 'bool' object has no attribute 'info`.

This commit changes the argument name to `do_log` to avoid the clash altogether.