Fixing PR remarks and adding unittests
Adding unittest to
* symlink and readlink (test.framework.filetools)
* set_default (test.framework.module_generator)

Currently the unittests pass, except for test.framework.module_generator
test_set_default because the environment is cleaned up in the test and LMod
complains about the cache.

The results for the unittests are:
python -m test.framework.filetools test_symlink_readlink_file
INFO: This is (based on) vsc.install.shared_setup 0.10.22
Filtered FileToolsTest tests using 'test_symlink_readlink_file',
retained 1/33 tests: test_symlink_readlink_file
.
----------------------------------------------------------------------
Ran 1 test in 0.740s

OK

python -m test.framework.module_generator test_set_default
INFO: This is (based on) vsc.install.shared_setup 0.10.22
Filtered TclModuleGeneratorTest tests using 'test_set_default', retained
1/16 tests: test_set_default
Filtered LuaModuleGeneratorTest tests using 'test_set_default', retained
1/16 tests: test_set_default
.E
======================================================================
ERROR: test_set_default (__main__.LuaModuleGeneratorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/Users/hvictor/Programs/easybuild/easybuild-framework/test/framework/module_generator.py",
line 186, in test_set_default
    self.modtool.load([module_name])
  File "easybuild/tools/modules.py", line 509, in load
    self.run_module('load', mod)
  File "easybuild/tools/modules.py", line 674, in run_module
    raise EasyBuildError("Changing environment as dictated by module
failed: %s (%s)", err, out)
EasyBuildError: 'Changing environment as dictated by module failed: name
\'false\' is not defined (stdout: \nfalse\n, stderr: Lmod has detected
the following error: The following module(s) are unknown:
"dummy"\n\nPlease check the spelling or version number. Also try "module
spider ..."\nIt is also possible your cache file is out-of-date try:\n
$ module --ignore-cache load "dummy"\n\n\n\n)'

----------------------------------------------------------------------
Ran 2 tests in 2.653s

FAILED (errors=1)